brands = [
    {"name": "Apple"},
    {"name": "Honor"},
    {"name": "Huawei"},
    {"name": "Infinix"},
    {"name": "Itel"},
    {"name": "Meizu"},
    {"name": "Motorola"},
    {"name": "Novey"},
    {"name": "POCO"},
    {"name": "Premier"},
    {"name": "Samsung"},
    {"name": "Xiaomi"},
    {"name": "ZTE"},
]

phones = [
    {
        "name": "Honor X8c",
        "brand": "Honor",
        "price": 2639000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x8c-midnight-black-8256-gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 19199000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Deep Blue"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-max-deep-blue-12-256-gb",
    },
    {
        "name": "Samsung Galaxy A17",
        "brand": "Samsung",
        "price": 2649000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a17-black-6128-gb",
    },
    {
        "name": "Apple iPhone 17 Pro",
        "brand": "Apple",
        "price": 17799000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Silver"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-silver-12-256-gb",
    },
    {
        "name": "Redmi 15",
        "brand": "Xiaomi",
        "price": 2499000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-redmi-15-midnight-black-8256-gb",
    },
    {
        "name": "Honor X9c",
        "brand": "Honor",
        "price": 3819000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Titanium Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x9c-titanium-black-8256-gb",
    },
    {
        "name": "Redmi Note 15",
        "brand": "Xiaomi",
        "price": 2389000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Night Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-note-15-point-night-black-6128-gb",
    },
    {
        "name": "Samsung Galaxy A57",
        "brand": "Samsung",
        "price": 5789000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Awesome Navy"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a57-point-awesome-navy-point-8256-gb",
    },
    {
        "name": "Honor X7d",
        "brand": "Honor",
        "price": 2499000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Desert Gold"],
        "link": "https://market.beeline.uz/smartfony/honor-x7d-desert-gold-6128-gb",
    },
    {
        "name": "Honor X7d",
        "brand": "Honor",
        "price": 2499000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Velvet Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x7d-velvet-black-6128-gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 4899000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "url?id=35",
    },
    {
        "name": "Samsung Galaxy S26",
        "brand": "Samsung",
        "price": 11449000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-s26-point-black-point-256-gb",
    },
    {
        "name": "Honor 600 Lite",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Desert Gold"],
        "link": "https://market.beeline.uz/smartfony/honor-600-lite-point-desert-gold-point-8256-gb",
    },
    {
        "name": "Honor X8d",
        "brand": "Honor",
        "price": 3599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x8d-point-black-point-8256-gb",
    },
    {
        "name": "Samsung Galaxy A56",
        "brand": "Samsung",
        "price": 4519000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Awesome Graphite"],
        "link": "url?id=39",
    },
    {
        "name": "Xiaomi 17T",
        "brand": "Xiaomi",
        "price": 6989000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-17t-point-black-point-12256-gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 19199000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Cosmic Orange"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-max-cosmic-orange-12-256-gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 4899000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Reddish"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-reddish-point-8256-gb",
    },
    {
        "name": "Samsung Galaxy S26 Ultra",
        "brand": "Samsung",
        "price": 15249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Cobalt Violet"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-s26-ultra-point-cobalt-violet-point-256-gb",
    },
    {
        "name": "Honor X7d",
        "brand": "Honor",
        "price": 2499000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Meteor Silver"],
        "link": "https://market.beeline.uz/smartfony/honor-x7d-meteor-silver-6128-gb",
    },
    {
        "name": "Honor 600 Lite",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Grey"],
        "link": "https://market.beeline.uz/smartfony/honor-600-lite-point-velvet-grey-point-8256-gb",
    },
    {
        "name": "Honor 600",
        "brand": "Honor",
        "price": 6777000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/honor-600-point-black-point-8256-gb",
    },
    {
        "name": "Xiaomi 17T Pro",
        "brand": "Xiaomi",
        "price": 9499000,
        "rom_options": [512],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-17t-pro-point-black-point-12512-gb",
    },
    {
        "name": "Redmi 15C",
        "brand": "Xiaomi",
        "price": 2349000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-15c-midnight-black-8256-gb",
    },
    {
        "name": "Redmi Note 14",
        "brand": "Xiaomi",
        "price": 2059000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/mobilnie-ustroystva0",
    },
    {
        "name": "Honor 400 Lite",
        "brand": "Honor",
        "price": 3299000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Grey"],
        "link": "https://market.beeline.uz/smartfony/honor-400-lite-velvet-grey-8256-gb",
    },
    {
        "name": "Honor 600 Lite",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Black"],
        "link": "https://market.beeline.uz/smartfony/honor-600-lite-point-velvet-black-point-8256-gb",
    },
    {
        "name": "Xiaomi 17T",
        "brand": "Xiaomi",
        "price": 7499000,
        "rom_options": [512],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-17t-point-black-point-12512-gb",
    },
    {
        "name": "Redmi 15C",
        "brand": "Xiaomi",
        "price": 2049000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-redmi-15c-black-6128-gb",
    },
    {
        "name": "Honor 400 5G",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/smartfon-honor-400-8256gb-midnight-black",
    },
    {
        "name": "Xiaomi 15T",
        "brand": "Xiaomi",
        "price": 5749000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-15t-black-12-256-gb",
    },
    {
        "name": "Honor 400 5G",
        "brand": "Honor",
        "price": 4999000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-4005-g-midnight-black-12256gb",
    },
    {
        "name": "ZTE Blade A76",
        "brand": "ZTE",
        "price": 1499000,
        "rom_options": [128],
        "ram_options": [4],
        "colors": ["Carbon Black"],
        "link": "https://market.beeline.uz/smartfony/zte-blade-a76-carbon-black-4-128-gb-new",
    },
    {
        "name": "ZTE Blade A56",
        "brand": "ZTE",
        "price": 1199000,
        "rom_options": [64],
        "ram_options": [4],
        "colors": ["Celestial Black"],
        "link": "https://market.beeline.uz/smartfony/zte-blade-a56-celestial-black-4-64-gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 19199000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Silver"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-max-silver-12-256-gb",
    },
    {
        "name": "Redmi Note 15 Pro",
        "brand": "Xiaomi",
        "price": 3699000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Night Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-note-15-pro-point-night-black-8256-gb",
    },
    {
        "name": "Redmi Note 15",
        "brand": "Xiaomi",
        "price": 2799000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Night Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-note-15-point-night-black-8256-gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 5249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-midnight-black-point-12256-gb",
    },
    {
        "name": "Samsung Galaxy A57",
        "brand": "Samsung",
        "price": 5789000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Awesome Grey"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a57-point-awesome-gray-point-8256-gb",
    },
    {
        "name": "Samsung Galaxy S26 Ultra",
        "brand": "Samsung",
        "price": 15249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-s26-ultra-point-black-point-256-gb",
    },
    {
        "name": "Honor X9c Smart",
        "brand": "Honor",
        "price": 2969000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Moonlight White"],
        "link": "https://market.beeline.uz/smartfony/honor-x9c-moonlight-white-8256-gb",
    },
    {
        "name": "Samsung Galaxy A36",
        "brand": "Samsung",
        "price": 3569000,
        "rom_options": [128],
        "ram_options": [8],
        "colors": ["Awesome Black"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a36-black-8128gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 5249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Reddish"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-reddish-point-12256-gb",
    },
    {
        "name": "Samsung Galaxy S25",
        "brand": "Samsung",
        "price": 8499000,
        "rom_options": [128],
        "ram_options": [12],
        "colors": ["Silver Shadow"],
        "link": "https://market.beeline.uz/smartfony/apple2",
    },
    {
        "name": "Honor X8c",
        "brand": "Honor",
        "price": 2639000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x8c-midnight-black-8256-gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 19199000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Deep Blue"],
        "link": "url?id=26",
    },
    {
        "name": "Samsung Galaxy A17",
        "brand": "Samsung",
        "price": 2649000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Black"],
        "link": "url?id=27",
    },
    {
        "name": "Apple iPhone 17 Pro",
        "brand": "Apple",
        "price": 17799000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Silver"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-silver-12-256-gb",
    },
    {
        "name": "Redmi 15",
        "brand": "Xiaomi",
        "price": 2499000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-redmi-15-midnight-black-8256-gb",
    },
    {
        "name": "Honor X9c",
        "brand": "Honor",
        "price": 3819000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Titanium Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x9c-titanium-black-8256-gb",
    },
    {
        "name": "Redmi Note 15",
        "brand": "Xiaomi",
        "price": 2389000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Night Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-note-15-point-night-black-6128-gb",
    },
    {
        "name": "Samsung Galaxy A57",
        "brand": "Samsung",
        "price": 5789000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Awesome Navy"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a57-point-awesome-navy-point-8256-gb",
    },
    {
        "name": "Honor X7d",
        "brand": "Honor",
        "price": 2499000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Desert Gold"],
        "link": "https://market.beeline.uz/smartfony/honor-x7d-desert-gold-6128-gb",
    },
    {
        "name": "Honor X7d",
        "brand": "Honor",
        "price": 2499000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Velvet Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x7d-velvet-black-6128-gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 4899000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-midnight-black-point-8256-gb",
    },
    {
        "name": "Samsung Galaxy S26",
        "brand": "Samsung",
        "price": 11449000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "url?id=36",
    },
    {
        "name": "Honor 600 Lite",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Desert Gold"],
        "link": "https://market.beeline.uz/smartfony/honor-600-lite-point-desert-gold-point-8256-gb",
    },
    {
        "name": "Honor X8d",
        "brand": "Honor",
        "price": 3599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x8d-point-black-point-8256-gb",
    },
    {
        "name": "Samsung Galaxy A56",
        "brand": "Samsung",
        "price": 4519000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Awesome Graphite"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a56-black-8256gb",
    },
    {
        "name": "Xiaomi 17T",
        "brand": "Xiaomi",
        "price": 6989000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-17t-point-black-point-12256-gb",
    },
    {
        "name": "Honor 600",
        "brand": "Honor",
        "price": 6777000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Golden White"],
        "link": "https://market.beeline.uz/smartfony/honor-600-point-golden-white-point-8256-gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 19199000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Cosmic Orange"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-max-cosmic-orange-12-256-gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 4899000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Reddish"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-reddish-point-8256-gb",
    },
    {
        "name": "Samsung Galaxy S26 Ultra",
        "brand": "Samsung",
        "price": 15249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Cobalt Violet"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-s26-ultra-point-cobalt-violet-point-256-gb",
    },
    {
        "name": "Honor X7d",
        "brand": "Honor",
        "price": 2499000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Meteor Silver"],
        "link": "https://market.beeline.uz/smartfony/honor-x7d-meteor-silver-6128-gb",
    },
    {
        "name": "Honor 600 Lite",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Grey"],
        "link": "https://market.beeline.uz/smartfony/honor-600-lite-point-velvet-grey-point-8256-gb",
    },
    {
        "name": "Honor 600",
        "brand": "Honor",
        "price": 6777000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/honor-600-point-black-point-8256-gb",
    },
    {
        "name": "Xiaomi 17T Pro",
        "brand": "Xiaomi",
        "price": 9499000,
        "rom_options": [512],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-17t-pro-point-black-point-12512-gb",
    },
    {
        "name": "Redmi 15C",
        "brand": "Xiaomi",
        "price": 2349000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-15c-midnight-black-8256-gb",
    },
    {
        "name": "Redmi Note 14",
        "brand": "Xiaomi",
        "price": 2059000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Midnight Black"],
        "link": "url?id=50",
    },
    {
        "name": "Honor 400 Lite",
        "brand": "Honor",
        "price": 3299000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Grey"],
        "link": "https://market.beeline.uz/smartfony/honor-400-lite-velvet-grey-8256-gb",
    },
    {
        "name": "Honor 400 Lite",
        "brand": "Honor",
        "price": 3349000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Black"],
        "link": "https://market.beeline.uz/smartfony/honor-400-lite-velvet-black-8256-gb",
    },
    {
        "name": "Honor 600 Lite",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Velvet Black"],
        "link": "https://market.beeline.uz/smartfony/honor-600-lite-point-velvet-black-point-8256-gb",
    },
    {
        "name": "Xiaomi 17T",
        "brand": "Xiaomi",
        "price": 7499000,
        "rom_options": [512],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-17t-point-black-point-12512-gb",
    },
    {
        "name": "Redmi 15C",
        "brand": "Xiaomi",
        "price": 2049000,
        "rom_options": [128],
        "ram_options": [6],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/mobilnie-ustroystva5",
    },
    {
        "name": "Honor 400 5G",
        "brand": "Honor",
        "price": 4599000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/smartfon-honor-400-8256gb-midnight-black",
    },
    {
        "name": "Xiaomi 15T",
        "brand": "Xiaomi",
        "price": 5749000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/xiaomi-15t-black-12-256-gb",
    },
    {
        "name": "Honor 400 5G",
        "brand": "Honor",
        "price": 4999000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-4005-g-midnight-black-12256gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 22449000,
        "rom_options": [512],
        "ram_options": [],
        "colors": ["Cosmic Orange"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-max-cosmic-orange-12-512-gb",
    },
    {
        "name": "ZTE Blade A76",
        "brand": "ZTE",
        "price": 1499000,
        "rom_options": [128],
        "ram_options": [4],
        "colors": ["Carbon Black"],
        "link": "url?id=60",
    },
    {
        "name": "Samsung Galaxy A07",
        "brand": "Samsung",
        "price": 1719000,
        "rom_options": [128],
        "ram_options": [4],
        "colors": ["Black"],
        "link": "url?id=61",
    },
    {
        "name": "ZTE Blade A56",
        "brand": "ZTE",
        "price": 1199000,
        "rom_options": [64],
        "ram_options": [4],
        "colors": ["Celestial Black"],
        "link": "https://market.beeline.uz/smartfony/zte-blade-a56-celestial-black-4-64-gb",
    },
    {
        "name": "Apple iPhone 17 Pro Max",
        "brand": "Apple",
        "price": 19199000,
        "rom_options": [256],
        "ram_options": [],
        "colors": ["Silver"],
        "link": "https://market.beeline.uz/smartfony/apple-iphone-17-pro-max-silver-12-256-gb",
    },
    {
        "name": "Redmi Note 15 Pro",
        "brand": "Xiaomi",
        "price": 3699000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Night Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-note-15-pro-point-night-black-8256-gb",
    },
    {
        "name": "Redmi Note 15",
        "brand": "Xiaomi",
        "price": 2799000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Night Black"],
        "link": "https://market.beeline.uz/smartfony/redmi-note-15-point-night-black-8256-gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 5249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Midnight Black"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-midnight-black-point-12256-gb",
    },
    {
        "name": "Samsung Galaxy A57",
        "brand": "Samsung",
        "price": 5789000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Awesome Grey"],
        "link": "https://market.beeline.uz/smartfony/ajib7",
    },
    {
        "name": "Samsung Galaxy S26 Ultra",
        "brand": "Samsung",
        "price": 15249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Black"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-s26-ultra-point-black-point-256-gb",
    },
    {
        "name": "Honor X9c Smart",
        "brand": "Honor",
        "price": 2969000,
        "rom_options": [256],
        "ram_options": [8],
        "colors": ["Moonlight White"],
        "link": "https://market.beeline.uz/smartfony/honor-x9c-moonlight-white-8256-gb",
    },
    {
        "name": "Samsung Galaxy A36",
        "brand": "Samsung",
        "price": 3569000,
        "rom_options": [128],
        "ram_options": [8],
        "colors": ["Awesome Black"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-a36-black-8128gb",
    },
    {
        "name": "Honor X9d",
        "brand": "Honor",
        "price": 5249000,
        "rom_options": [256],
        "ram_options": [12],
        "colors": ["Reddish"],
        "link": "https://market.beeline.uz/smartfony/honor-x9d-point-reddish-point-12256-gb",
    },
    {
        "name": "Samsung Galaxy S25",
        "brand": "Samsung",
        "price": 8499000,
        "rom_options": [128],
        "ram_options": [12],
        "colors": ["Silver Shadow"],
        "link": "https://market.beeline.uz/smartfony/samsung-galaxy-s25-silver-shadow-12128-gb",
    },
]


print(len(phones))